name: Dastardly Scan

on:
  push:
    branches: [ main ]

permissions:
  checks: write
  
jobs:
  scan:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@main
      
    - name: Run Dastardly Scan Action
      continue-on-error: true
      uses: PortSwigger/dastardly-github-action@main
      with:
        target-url: 'https://ginandjuice.shop' 
        output-filename: 'dastardly-report.xml'

    - name: Upload results
      uses: actions/upload-artifact@main
      with:
        name: dastardly-report.xml
        path: ./

    - name: Publish Test Report
      if: always()
      uses: mikepenz/action-junit-report@main
      with:
        report_paths: '**/dastardly-report.xml'
        require_tests: true
        summary: true
        job_summary: true
